#!/usr/bin/env bash

set -euxo pipefail

# Function for displaying help info
help_info() {
  echo "
Usage: ${0##*/} [options]
Build a release .tar.gz for Linux.

Options:
  -h, --help     Display this help and exit.
  --flatpak      Set GOOP_BUNDLE_TYPE=flatpak so that this can be included in system info
  "
}

# Parse all arguments manually
while [[ $# -gt 0 ]]; do
    case $1 in
        -h|--help)
            help_info
            exit 0
            ;;
        --flatpak)
            export GOOP_BUNDLE_TYPE=flatpak
            shift
            ;;
        --)
            shift
            break
            ;;
        -*)
            echo "Unknown option: $1" >&2
            help_info
            exit 1
            ;;
        *)
            echo "Error: Unexpected argument: $1" >&2
            help_info
            exit 1
            ;;
    esac
done

export GOOP_BUNDLE=true

target_dir="${CARGO_TARGET_DIR:-target}"

version="$(script/get-crate-version goop)"
# Set RELEASE_VERSION so it's compiled into GPUI and it knows about the version.
export RELEASE_VERSION="${version}"

commit=$(git rev-parse HEAD | cut -c 1-7)

version_info=$(rustc --version --verbose)
host_line=$(echo "$version_info" | grep host)
target_triple=${host_line#*: }
musl_triple=${target_triple%-gnu}-musl
remote_server_triple=${REMOTE_SERVER_TARGET:-"${musl_triple}"}
rustup_installed=false

if command -v rustup >/dev/null 2>&1; then
    rustup_installed=true
fi

export CC=$(which clang)

# Build binary in release mode
export RUSTFLAGS="${RUSTFLAGS:-} -C link-args=-Wl,--disable-new-dtags,-rpath,\$ORIGIN/../lib"
cargo build --release --target "${target_triple}" --package goop

# Strip debug symbols and save them for upload to DigitalOcean
objcopy --only-keep-debug "${target_dir}/${target_triple}/release/goop" "${target_dir}/${target_triple}/release/goop.dbg"
objcopy --strip-debug "${target_dir}/${target_triple}/release/goop"

gzip -f "${target_dir}/${target_triple}/release/goop.dbg"

# Move everything that should end up in the final package
# into a temp directory.
temp_dir=$(mktemp -d)
goop_dir="${temp_dir}/goop.app"

# Binary
mkdir -p "${goop_dir}/bin" "${goop_dir}/libexec"
cp "${target_dir}/${target_triple}/release/goop" "${goop_dir}/libexec/goop"
cp "${target_dir}/${target_triple}/release/goop" "${goop_dir}/bin/goop"

# Libs
find_libs() {
    ldd ${target_dir}/${target_triple}/release/goop |\
        cut -d' ' -f3 |\
        grep -v '\<\(libstdc++.so\|libc.so\|libgcc_s.so\|libm.so\|libpthread.so\|libdl.so\|libasound.so\)'
}

mkdir -p "${goop_dir}/lib"
rm -rf "${goop_dir}/lib/*"
cp $(find_libs) "${goop_dir}/lib"

# Icons
mkdir -p "${goop_dir}/share/icons/hicolor/512x512/apps"
cp "desktop/resources/icon.png" "${goop_dir}/share/icons/hicolor/512x512/apps/goop.png"
mkdir -p "${goop_dir}/share/icons/hicolor/1024x1024/apps"
cp "desktop/resources/icon@2x.png" "${goop_dir}/share/icons/hicolor/1024x1024/apps/goop.png"

# .desktop
export DO_STARTUP_NOTIFY="true"
export APP_CLI="goop"
export APP_ICON="goop"
export APP_ARGS="%U"
export APP_NAME="Goop"

mkdir -p "${goop_dir}/share/applications"
envsubst < "desktop/resources/goop.desktop.in" > "${goop_dir}/share/applications/goop.desktop"

# Create archive out of everything that's in the temp directory
arch=$(uname -m)
target="linux-${arch}"
archive="goop-${target}.tar.gz"

rm -rf "${archive}"
remove_match="goop(-[a-zA-Z0-9]+)?-linux-$(uname -m)\.tar\.gz"
ls "${target_dir}/release" | grep -E ${remove_match} | xargs -d "\n" -I {} rm -f "${target_dir}/release/{}" || true
tar -czvf "${target_dir}/release/$archive" -C ${temp_dir} "goop.app"
