[package]
name = "goop"
version.workspace = true
edition.workspace = true
publish.workspace = true

[[bin]]
name = "goop"
path = "src/main.rs"

[package.metadata.packager]
name = "Goop"
product-name = "Goop"
description = "A native NIP-17 client to chat with your clankers (and friends)"
identifier = "com.dergigi.goop"
category = "SocialNetworking"
version = "2.11.1"
out-dir = "../dist"
before-packaging-command = "cargo build --locked --release --features gpui_macos/runtime_shaders"
resources = ["Cargo.toml", "src"]
icons = [
    "resources/32x32.png",
    "resources/128x128.png",
    "resources/128x128@2x.png",
    "resources/icon.icns",
    "resources/icon.ico",
]

[package.metadata.packager.macos]
info-plist-path = "resources/Info.plist"

[dependencies]
assets = { path = "../crates/assets" }
workspace = { path = "../crates/workspace" }
ui = { path = "../crates/ui" }
theme = { path = "../crates/theme" }
common = { path = "../crates/common" }
state = { path = "../crates/state" }
chat = { path = "../crates/chat" }
settings = { path = "../crates/settings" }
update_check = { path = "../crates/update_check" }
person = { path = "../crates/person" }

gpui.workspace = true
gpui_platform.workspace = true
gpui_linux.workspace = true
gpui_windows.workspace = true
gpui_macos.workspace = true
reqwest_client.workspace = true

log.workspace = true
tracing-subscriber.workspace = true
nostr-sdk.workspace = true

[build-dependencies]
embed-resource = "=3.0.11"
